SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{5CA0A9E60B892D2A}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{60FD565F7DFBE6A4}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogInventoryItem "{60FD565F20A453B3}" {
     m_bEnabled 0
    }
   }
  }
 }
}