SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{5C630E453BCB39DC}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{663ED4D474802BBD}" {
     m_sEntityPrefab "{E598D6291182ACDA}Prefabs/Items/Equipment/Radios/Radio_R187_INDFOR.et"
    }
    SCR_EntityCatalogInventoryItem "{663ED4D472D70424}" {
     m_sEntityPrefab "{34680EAA5D384511}Prefabs/Items/Equipment/Radios/Radio_R168_INDFOR.et"
    }
   }
  }
 }
}